name: Update Leaderboard

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Update leaderboard
        run: python update_leaderboard.py --owner ${{ github.repository_owner }} --repo ${{ github.event.repository.name }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md leaderboard.html
          if ! git diff --cached --quiet; then
            git commit -m "Update leaderboard"
            git push
          else
            echo "No changes to commit"
          fi
